### PR TITLE
redirect /newsletter to mailchimp signup url

### PR DESCRIPTION
**Pull request by robobunny**
I'm working on Issue 909 on the redwood framework, trying to encourage community engagement upon completion of the create-redwood-app script.

This PR adds a redirect in the netlify.toml so that `redwoodjs.com/newsletter` redirects to the unwieldy mailchimp url `https://redwoodjs.us19.list-manage.com/subscribe/post?u=0c27354a06a7fdf4d83ce07fc&id=09f634eea4`.

This way, I can add the cleaner `redwoodjs.com/newsletter` url to the copy at the end of the CRA script.

Cheers!

### CODE REVIEW

**Comment by Tobbe** [comment]
A PR was recently merged that adds support for the rules in netlify.toml to local dev as well. I'm curious to know if you've tried the redirect on localhost. Did it work?

**Comment by robobunny** [comment]
> A PR was recently merged that adds support for the rules in netlify.toml to local dev as well. I'm curious to know if you've tried the redirect on localhost. Did it work?

Hmmm... so I didn't initially try to run a dev server at all, just tried it with the deploy preview from Netlify. I'm a bit dense with this so maybe you can help? In my cloned repo I ran `yarn install` then `yarn build` then `yarn dev` and I got:

```
// . . . 

Error: Cannot find module 'fs/promises'
Require stack:
- /home/william/Desktop/Robobunny/redwoodjs/redwoodjs.com/lib/middleware/use-redirects.js
- /home/william/Desktop/Robobunny/redwoodjs/redwoodjs.com/node_modules/live-server/index.js
- /home/william/Desktop/Robobunny/redwoodjs/redwoodjs.com/node_modules/live-server/live-server.js

// . . .
```
and if I run `yarn netlify` I get:

```
// . . .

◈ No "targetPort" option specified or detected.
error Command failed with exit code 1.

// . . .
```
Here probably isn't the place to get into it, but maybe there's something obvious I'm missing?

```
$ node -v
v12.18.3

$ yarn -v
1.22.4

$ npm -v
6.14.8
```

So the answer to your original question is: no, I haven't tried it on localhost ... yet.

**Comment by robobunny** [comment]
Ok so it works with node version >= 12.19 apparently. 

Also had to add 
```
targetPort = 8081
framework = "#custom"
```
to `netlify.toml` to be able to run `yarn netlify` successfully... idk.

## The answer to your question

No, `localhost:8080/newsletter` does not redirect, neither after having run `yarn dev` nor `yarn netlify`. I wonder why...

**Comment by dthyresson** [comment]
FYI - the ‘yarn netlify ’ uses

https://www.netlify.com/products/dev/

So that redirects and such work

**Comment by Tobbe** [comment]
`yarn dev` is all you should need when running locally. Great that you got it working, and thanks for verifying the redirect 👍 It was I who wrote that PR, so I was curious/hoping to see if the redirect would work as expected 🙂

**Review by Tobbe — APPROVED** [review]
I tested these changes locally, and it works great for me as well. LGTM!
